export class CustCompanyMgmntShrholderObj {
    CustCompanyMgmntShrholderId : any;
    CustCompanyId: any;
    MgmntShrholderName: any;
    MrJobPositionCode: any;
    SharePrcnt: number;
    IsSigner: any;
    IsOwner : any;
    MrIdTypeCode: any;
    IdNo: any;
    IdExpiredDt: any;
    BirthPlace: any;
    BirthDt: any;
    MrGenderCode: any;
    MrNationalityCode: any;
    NationalityCountryCode: any;
    TaxIdNo: any;
    MobilePhnNo: any;
    Email: any;
    MrIndustryTypeCode: any;
    EstablishmentDt: any;
    MrCompanyTypeCode: any;
    MrCustTypeCode: any;
    ShareholderCustNo: any;
    MrCustModelCode : any;
    IsActive: any;
    CustId: any;
    ShareholderId: any;
    RowVersion: any;
}