export class CustPersonalContactPersonObj {
    CustPersonalContactPersonId: number;
    CustId: number;
    ContactPersonName: string;
    MrIdTypeCode: string;
    IdNo: string;
    BirthPlace: string;
    BirthDt: Date;
    MotherMaidenName: string;
    MrGenderCode: string;
    MrReligionCode: string;
    IdExpiredDt : Date;
    TaxIdNo : string;
    MrEducationCode: string;
    MrJobProfessionCode: string;
    MrMaritalStatCode: string;
    MrNationalityCode: string;
    NationalityCountryCode: string;
    MrCustRelationshipCode: string;
    IsEmergencyContact: boolean;
    IsFamily: boolean;
    MobilePhnNo1: string;
    MobilePhnNo2: string;
    MobilePhnNo3: string;
    IsWaMobilePhnNo1: boolean;
    IsWaMobilePhnNo2: boolean;
    IsWaMobilePhnNo3: boolean;
    Email: string;
    Addr: string;
    AreaCode1: string;
    AreaCode2: string;
    AreaCode3: string;
    AreaCode4: string;
    Phn1: string;
    PhnExt1: string;
    PhnArea1: string;
    Phn2: string;
    PhnExt2: string;
    PhnArea2: string;
    Phn3: string;
    PhnExt3: string;
    PhnArea3: string;
    City: string;
    SubZipcode: string;
    Zipcode : string;
    ContactPersonCustNo: string;
    RowVersion: string;
}
