import { NewCustHeaderComponent } from 'app/customer/sharing-component/new-cust-header/new-cust-header.component';

export {BankComponent} from '../bank/bank.component';
export {EmployeeAddComponent} from '../employee/employee-add/employee-add.component';
export{SelfCustomContainerNewCustHeaderComponent} from "app/customer/sharing-component/self-custom-container-new-cust-header/self-custom-container-new-cust-header.component";
export{SelfCustomContainerThirdPartyFormComponent} from "app/customer/sharing-component/self-custom-container-third-party-form/self-custom-container-third-party-form.component";
export{SelfCustomContainerCustAttrComponent} from "app/customer/sharing-component/self-custom-container-cust-attr/self-custom-container-cust-attr.component";
export{SelfCustomCustomerPersonalAddressComponent} from "app/customer/customer-personal/self-custom-customer-personal/self-custom-customer-personal-address/self-custom-customer-personal-address.component";
export{SelfCustomContainerViewVendorAttrComponent} from "app/view/vendor/self-custom-container-view-vendor-attr/self-custom-container-view-vendor-attr.component";
export{SelfCustomContainerCustViewDocComponent} from "app/view/self-custom-cust-view/self-custom-container-cust-view-doc/self-custom-container-cust-view-doc.component";
export{SelfCustomContainerCustViewFinDataAttrComponent} from "app/view/self-custom-cust-view/self-custom-container-cust-view-fin-data-attr/self-custom-container-cust-view-fin-data-attr.component";
export{UpdateCustomerPersonalDetailComponent} from "app/customer/customer-update-master/customer-update-master-detail/personal/update-customer-personal-detail/update-customer-personal-detail.component";
export{SelfCustomCustFinDataTabComponent} from "app/customer/cust-fin-data-tab/self-custom-fin-data-tab.component"
export{CustFinDataTabComponent} from "app/customer/cust-fin-data-tab/cust-fin-data-tab.component"
export{SelfCustomCustFinDataComponent} from "app/customer/cust-fin-data-tab/self-custom-cust-fin-data.component"
export{CustomerViewAsliRiComponent} from 'app/view/customer-view/customer-view-asli-ri/customer-view-asli-ri.component';
export{ CustomerViewCbasSlikComponent } from 'app/view/customer-view/customer-view-cbas-slik/customer-view-cbas-slik.component';
export{SelfCustomCustomerViewIframeGenericComponent} from "app/view/self-custom-cust-view/self-custom-customer-view-iframe-generic/self-custom-customer-view-iframe-generic.component";
export{SelfCustomContainerCustViewFinDataBankStmntComponent} from "app/view/self-custom-cust-view/self-custom-container-cust-view-fin-data-bank-stmnt/self-custom-container-cust-view-fin-data-bank-stmnt.component";
export{SelfCustomCustExposureViewComponent} from "app/view/self-custom-cust-view/self-custom-cust-exposure-view/self-custom-cust-exposure-view.component";
export{SelfCustomContainerViewExposureBucketComponent} from "app/view/self-custom-cust-view/self-custom-container-view-exposure-bucket/self-custom-container-view-exposure-bucket.component";
export{SelfCustomContainerDmsIframeComponent} from "app/shared/self-custom-container-dms-iframe/self-custom-container-dms-iframe.component";
export { SelfCustomContainerCustAttrSectionComponent } from 'app/customer/self-custom-container-cust-attr-section/self-custom-container-cust-attr-section.component';
export { CustomCustAttrSectionComponent } from 'app/customer/custom-cust-attr-section/custom-cust-attr-section.component';
export { CustomAssetMasterAddEditParentComponent } from 'app/asset/custom-asset-master/custom-asset-master-add-edit-parent/custom-asset-master-add-edit-parent.component';
export { CustomAssetMasterDetailParentComponent } from 'app/asset/custom-asset-master/custom-asset-master-add-edit-parent/custom-asset-master-detail-parent/custom-asset-master-detail-parent.component';
export { CustomShareholderListingComponent } from 'app/customer/sharing-component/custom-shareholder-listing/custom-shareholder-listing.component';
export { CustomCustomerCompanyAddressComponent } from 'app/customer/customer-company/custom-customer-company-address/custom-customer-company-address.component';
export{SelfCustomCustomerViewCoyFinancialComponent} from "app/view/self-custom-cust-view/self-custom-customer-view-coy-financial/self-custom-customer-view-coy-financial.component";
export{SelfCustomContainerFamilyListingComponent} from "app/customer/sharing-component/self-custom-container-family-listing/self-custom-container-family-listing.component";
export{SelfCustomCustomerEmergencyContactComponent} from "app/customer/customer-personal/self-custom-customer-personal/self-custom-customer-emergency-contact/self-custom-customer-emergency-contact.component";
export { CustomDocumentSurveyTaskViewComponent } from 'app/view/survey-task-view/custom-document-survey-task-view/custom-document-survey-task-view.component';
export { ViewSurveyTaskDetailComponent } from 'app/view/survey-task-view/view-survey-task-detail/view-survey-task-detail.component';
export { SelfCustomViewPefindoScoreComponent } from 'app/view/self-custom-pefindo-view/self-custom-view-pefindo-score/self-custom-view-pefindo-score.component';
export { CoaDetailComponent } from 'app/common-setting/coa/coa-detail/coa-detail.component';
export { CustomCoaSchemeDetailComponent } from 'app/common-setting/custom-coa-scheme/custom-coa-scheme-detail/custom-coa-scheme-detail.component';
export { SelfCustomContainerHolidayDetailComponent } from 'app/common-setting/holiday-scheme/self-custom-container-holiday-detail/self-custom-container-holiday-detail.component';
export { SelfCustomContainerWorkingHourDDetailComponent } from 'app/common-setting/working-hour-scheme/self-custom-container-working-hour-d-detail/self-custom-container-working-hour-d-detail.component';
export { CustomSurveyResultReviewDetailComponent } from 'app/survey/custom-survey-result-review-detail/custom-survey-result-review-detail.component';
export { SelfCustomContainerSurveyTaskResultDetailComponent } from 'app/survey/self-custom-container-survey-task-result-detail/self-custom-container-survey-task-result-detail.component';
export { SelfCustomContainerSurveyTaskResultUploadDocComponent } from 'app/survey/self-custom-container-survey-task-result-upload-doc/self-custom-container-survey-task-result-upload-doc.component';
export { SelfCustomContainerVendorHoInfoComponent } from 'app/vendor/vendor-ho/self-custom-container-vendor-ho-info/self-custom-container-vendor-ho-info.component';
export { SelfCustomContainerVendorBranchInfoComponent } from 'app/vendor/vendor-branch/self-custom-container-vendor-branch-info/self-custom-container-vendor-branch-info.component';
export { SelfCustomContainerVendorBranchInfoXComponent } from 'app/impl/vendor/vendor-branch/self-custom-container-vendor-branch-info/self-custom-container-vendor-branch-info-x.component';
export { SelfCustomNewCustHeaderShareholderComponent } from 'app/customer/sharing-component/new-cust-header/self-custom-new-cust-header.component';
export { SelfCustomBouwheerCompanyIndustryInfo } from 'app/customer/bouwheer/self-custom-bouwheer-company-industry-info.component';
export { SelfCustomCustCompanyIndustryInfo } from 'app/customer//customer-company/self-custom-customer-company/self-custom-cust-company-industry-info/self-custom-cust-company-industry-info.component';
export { SelfCustomContainerOcrCustPersonalComponent } from 'app/customer/sharing-component/self-custom-container-ocr-cust-personal/self-custom-container-ocr-cust-personal.component';
export { SelfCustomContainerOcrVendorComponent } from 'app/vendor/self-custom-container-npwp-vendor/self-custom-container-ocr-vendor.component';
export { CustomFundingCompanyAddEditComponent } from 'app/vendor/funding-company/custom-funding-company-add-edit/custom-funding-company-add-edit.component';
export { CustomAssetMasterAddEditChildComponent } from 'app/asset/custom-asset-master/custom-asset-master-add-edit-child/custom-asset-master-add-edit-child.component';
export { CustomAssetMasterDetailChildComponent } from 'app/asset/custom-asset-master/custom-asset-master-add-edit-child/custom-asset-master-detail-child/custom-asset-master-detail-child.component';
export { CustomUpdateCustomerPersonalDetailComponent} from 'app/customer/self-custom-container-customer-update/personal/update-customer-personal-detail/custom-update-customer-personal-detail.component';
export { CustomUpdateCustomerJobDataComponent } from 'app/customer/self-custom-container-customer-update/personal/update-customer-job-data/custom-update-customer-job-data.component';
export { CustomUpdateCustomerFinDataComponent } from 'app/customer/self-custom-container-customer-update/personal/update-customer-fin-data/custom-update-customer-fin-data.component';
export { CustomUpdateCustomerFamilyComponent } from 'app/customer/self-custom-container-customer-update/personal/update-customer-family/custom-update-customer-family.component';
export { CustomUpdateCustomerEmergencyComponent } from 'app/customer/self-custom-container-customer-update/personal/update-customer-emergency/custom-update-customer-emergency.component';
export { CustomUpdateCustomerAddressComponent } from 'app/customer/self-custom-container-customer-update/personal/update-customer-address/custom-update-customer-address.component';
export { CustomUpdateCustomerMgmntShareholderComponent } from 'app/customer/self-custom-container-customer-update/company/update-customer-mgmnt-shareholder/custom-update-customer-mgmnt-shareholder.component';
export { CustomUpdateCustomerContactInfoComponent } from 'app/customer/self-custom-container-customer-update/company/update-customer-contact-info/custom-update-customer-contact-info.component';
export { CustomUpdateCustomerCompanyLegalDocComponent } from 'app/customer/self-custom-container-customer-update/company/update-customer-company-legal-doc/custom-update-customer-company-legal-doc.component';
export { CustomUpdateCustomerCompanyFinDataComponent } from 'app/customer/self-custom-container-customer-update/company/update-customer-company-fin-data/custom-update-customer-company-fin-data.component';
export { CustomUpdateCustomerCompanyDetailComponent } from 'app/customer/self-custom-container-customer-update/company/update-customer-company-detail/custom-update-customer-company-detail.component';
export { ContainerCustLegalDocUploadComponent } from "app/customer/cust-legal-doc/container-cust-legal-doc-upload/container-cust-legal-doc-upload.component";
export { SelfCustomContainerDmsIframeProjectComponent } from 'app/common-setting/Project/self-custom-container-dms-iframe-project/self-custom-container-dms-iframe-project.component';
export { SelfCustomCustViewComponent } from 'app/view/self-custom-cust-view/self-custom-cust-view/self-custom-cust-view.component';
export { CustomFundingCompanyAddEditXComponent } from 'app/vendor/funding-company/custom-funding-company-add-edit-x/custom-funding-company-add-edit-x.component';
export { FundingCompanyDetailComponent} from 'app/view/vendor/vendor-funding-company-view/funding-company-detail.component';
export { VendorBranchOfficeMemberAddXComponent } from 'app/impl/vendor/vendor-branch/vendor-branch-office-member-add-x/vendor-branch-office-member-add-x.component';