export class ResNegativeCustObj {
    NegativeCustId: number;
    CustId: number;
    CustNo: string;
    CustName: string;
    CustFullName: string;
    MrCustTypeCode: string;
    MrIdTypeCode: string;
    IdNo: string;
    TaxIdNo: string;
    IdExpiredDt: Date;
    MrGenderCode: string;
    BirthPlace: string;
    BirthDt: Date;
    MotherMaidenName: string;
    MrNegCustSourceCode: string;
    MrNegCustTypeCode: string;
    LegalAddr: string;
    AreaCode1: string;
    AreaCode2: string;
    AreaCode3: string;
    AreaCode4: string;
    Zipcode: string;
    City: string;
    PhnArea1: string;
    Phn1: string;
    PhnExt1: string;
    PhnArea2: string;
    Phn2: string;
    PhnExt2: string;
    PhnArea3: string;
    Phn3: string;
    PhnExt3: string;
    FaxArea: string;
    Fax: string;
    MobilePhn: string;
    NegCustCause: string;
    Notes: string;
    IsActive: boolean;
    MrCustModelCode: string;
    IsVip: boolean;
    OriginalOfficeCode: string;
    IsAffiliateWithMf: boolean;
    VipNotes: string;
    MrCompanyTypeCode: string;
    IsRestInPeace: boolean;
    RowVersion: string;

    constructor() {
        this.NegativeCustId = 0;
        this.CustId = 0;
        this.CustNo = "";
        this.CustName = "";
        this.CustFullName = "";
        this.MrCustTypeCode = "";
        this.MrIdTypeCode = "";
        this.IdNo = "";
        this.TaxIdNo = "";
        this.IdExpiredDt = new Date();
        this.MrGenderCode = "";
        this.BirthPlace = "";
        this.BirthDt = new Date();
        this.MotherMaidenName = "";
        this.MrNegCustSourceCode = "";
        this.MrNegCustTypeCode = "";
        this.LegalAddr = "";
        this.AreaCode1 = "";
        this.AreaCode2 = "";
        this.AreaCode3 = "";
        this.AreaCode4 = "";
        this.Zipcode = "";
        this.City = "";
        this.PhnArea1 = "";
        this.Phn1 = "";
        this.PhnExt1 = "";
        this.PhnArea2 = "";
        this.Phn2 = "";
        this.PhnExt2 = "";
        this.PhnArea3 = "";
        this.Phn3 = "";
        this.PhnExt3 = "";
        this.FaxArea = "";
        this.Fax = "";
        this.MobilePhn = "";
        this.NegCustCause = "";
        this.Notes = "";
        this.IsActive = false;
        this.MrCustModelCode = "";
        this.IsVip = false;
        this.OriginalOfficeCode = "";
        this.IsAffiliateWithMf = false;
        this.VipNotes = "";
        this.MrCompanyTypeCode = "";
        this.IsRestInPeace = false;
        this.RowVersion = "";
    }
}  